### ISSUE TITLE
using to export vtk from existing xplt file(s).

### ISSUE THREAD

**Issue by tcdoe** [Nobregaigor/febio-python#2]
Hello, and thank you for this work!
I hope this question isn't silly.
I am looking for a way to parse/import an xlpt file, and then just export all the states as a VTK file, any type that can be imported into ParaView.
Basically I just need to mimic FebioStudio's "save as" function that outputs the states.
I might also be using this febio-python for other stuff too, but this is my most important need right now.
I have not read the code here, and am not a super expert coder but can get things done.
Thanks for any info, and best regards,
-tcdoe

**Comment by Nobregaigor** [comment]
Hello @tcdoe. I apologize for the late response; I have not had time to keep track of issues on this package as this was not my main focus lately. 

I have updated this entire package, making it easier to read/understand and manage different parts of the FEBio data formats. Additionally, I have included `febio_to_vtk`, which converts either a `.feb` or `.xplt` or both into vtk file formats. I am still experimenting with this function, so be careful when using it. Check [examples/febio_container/convert_to_vtk.py](url) for a simple example on how to use it. I will be working on a proper documentation and some additional examples later.

_Note: You can also use the new `febio_to_pyvista`, which allows you to plot directly from python._
